### ISSUE TITLE
최초 프로파일 변경

### ISSUE THREAD

**Issue by enif-lee** [lakin32/lakin32.github.io#3]
## Tasks

- [x] 이메일 변경 jinseoung_lee@naver.com
- [x] Hybrid Application & Full-Stack Developer 추가
- [x] 생년월일 삭제
- [x] 블로그 링크 추가
